# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: bwzou
description: > # this means to ignore newlines until "baseurl:"
 这是本人的博客，记录自己的点点滴滴！
baseurl: "/bwzou" # the subpath of your site, e.g. /blog
url: "https://bwzou.github.io/bwzou/"
permalink: :title/
full-url: "https://bwzou.github.io/bwzou/" # the base hostname & protocol for your site


# CSS
sass:
  style: compressed

# Comments - Go to Disqus.com > sign up > get the short-name > insert it here
disqus-shortname: 

# Tracker
analytics: UA-83979019-1

# Form Settings
#
# Contact form can be enabled by getting an API key from https://getsimpleform.com/
simpleform-token: b6d4be9b039b666b3311e1ddcbfb577c

# Redirect users after submitting the form
redirect-to: https://bwzou.github.io/bwzou/thank-you/

# Site version
version: 0.9

# socket 
port: 4001

# Post date background - This will change the background of the post date and tag ribbon according to the theme. If set to no default green background will be used. If yes then the theme color scheme is used.

change-date-bg: no


# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"
incremental: false

include: [_pages] # Includes files inside _pages directory [Do not remove this]

author:
  name: bwzou
  image: bwzou.jpg # The author image will be shown on the header. Place this image in /images/ folder.
  about: bwzou是一个帅帅的前端工程师！！
  twitter: bwzou  # https://twitter.com/ is automatically added
  facebook: bwzou # https://facebook.com/ is automatically added
  email: bwzou1@gmail.com # mailto: is automatically added
  
gems: 
  - jekyll-seo-tag
  - jekyll-paginate